title: "Buldezir"
description: >- # this means to ignore newlines until "baseurl:"
  Note: Last chance to do it before apple stop support of x86 platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: buldezir
theme: minima
